name : test0
on:
  workflow_dispatch:
      inputs:
          publish:
              type: boolean
              description: Publish extension
              default: true
          pre-release:
              type: boolean
              description: Publish for devs
              default: false

jobs:
    build:
        runs-on: ubuntu-latest
        defaults:
          run:
            shell: bash
        steps:
          - run : |
              odd="true"
              echo "version is pre-release: ${odd}"
              [[ "${odd}" == 'true' && "${{github.event.inputs.pre-release}}" == "true" ]] && release="true" || release="false"
              echo "RELEASE=$release" >> $GITHUB_ENV
              
          - run : echo $RELEASE
          - name: Early exit
            run: |
              
              gh run cancel ${{ github.run_id }}
              gh run watch ${{ github.run_id }}
            env:
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
