name : test0
on:
  workflow_dispatch:
      inputs:
          publish:
              type: boolean
              description: Publish extension
              default: true
          pre-release:
              type: boolean
              description: Publish for devs
              default: false

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
          - run : export ODD_VERSION="true"
          - run : export RELEASE="false" && [[ $ODD_VERSION == 'true' && ${{github.event.inputs.pre-release }} == 'true' ]] && "true"
          - run : echo $PRE_RELEASE
            env : 
              PRE_RELEASE: ${{ env.RELEASE=='true' && '--pre' || 'lol' }}
